# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_files\UI\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 550)
        Form.setStyleSheet("background: rgb(43, 43, 43)")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(260, 20, 314, 42))
        self.label.setStyleSheet("color: rgb(206, 206, 206)")
        self.label.setObjectName("label")
        self.add_category = QtWidgets.QPushButton(Form)
        self.add_category.setGeometry(QtCore.QRect(590, 500, 211, 41))
        self.add_category.setStyleSheet("font-size: 20px;\n"
                                        "color: rgb(163, 163, 163);\n"
                                        "border-radius: 10px;\n"
                                        "border: 1px solid rgb(0, 0, 0)")
        self.add_category.setObjectName("add_category")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(50, 80, 751, 401))
        self.scrollArea.setStyleSheet("background-color: rgb(22, 22, 22);\n"
                                      "")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 732, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.storage = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.storage.setGeometry(QtCore.QRect(0, 10, 721, 51))
        self.storage.setStyleSheet("color: rgb(198, 0, 3);\n"
                                   "font-size: 25px;\n"
                                   "text-align: left;\n"
                                   "padding-left: 15px;\n"
                                   "background-color: rgb(113, 113, 113);\n"
                                   "border-radius: 10px;\n"
                                   "border: 1px solid rgb(168, 0, 2);")
        self.storage.setObjectName("storage")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.change_password = QtWidgets.QPushButton(Form)
        self.change_password.setGeometry(QtCore.QRect(50, 500, 161, 41))
        self.change_password.setStyleSheet("font-size: 20px;\n"
                                           "color: rgb(163, 163, 163);\n"
                                           "border-radius: 10px;\n"
                                           "border: 1px solid rgb(0, 0, 0)")
        self.change_password.setObjectName("change_password")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Secret Storage"))
        self.label.setText(_translate("Form",
                                      "<html><head/><body><p><span style=\" font-size:26pt;\">Добро пожаловать!</span></p></body></html>"))
        self.add_category.setText(_translate("Form", "Добавить хранилище"))
        self.storage.setText(_translate("Form", "Описание"))
        self.change_password.setText(_translate("Form", "Сменить пароль"))
