# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app\designer_files\UI\new_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiForm(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(850, 550)
        Form.setStyleSheet("background: rgb(43, 43, 43)")
        self.login = QtWidgets.QLineEdit(Form)
        self.login.setGeometry(QtCore.QRect(210, 130, 471, 61))
        self.login.setStyleSheet("color: rgb(163, 163, 163);\n"
                                 "font-size: 18px;\n"
                                 "border-radius: 10px;\n"
                                 "border: 2px solid rgb(100, 0, 0);\n"
                                 "background-color: rgb(79, 79, 79)")
        self.login.setText("")
        self.login.setObjectName("login")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.back.setStyleSheet("font-size: 16px;\n"
                                "color: rgb(163, 163, 163);\n"
                                "border-radius: 10px;\n"
                                "border: 1px solid rbg(0, 0, 0)")
        self.back.setObjectName("back")
        self.pass_changed = QtWidgets.QLabel(Form)
        self.pass_changed.setGeometry(QtCore.QRect(320, 20, 201, 33))
        self.pass_changed.setStyleSheet("color: rgb(0, 211, 0)")
        self.pass_changed.setObjectName("pass_changed")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(210, 220, 184, 29))
        self.label_2.setStyleSheet("color: rgb(163, 163, 163);\n"
                                   "font-size: 18px;")
        self.label_2.setObjectName("label_2")
        self.login_label = QtWidgets.QLabel(Form)
        self.login_label.setEnabled(True)
        self.login_label.setGeometry(QtCore.QRect(340, 90, 150, 31))
        self.login_label.setStyleSheet("color: rgb(234, 0, 3)")
        self.login_label.setObjectName("login_label")
        self.password_label = QtWidgets.QLabel(Form)
        self.password_label.setEnabled(True)
        self.password_label.setGeometry(QtCore.QRect(410, 220, 163, 31))
        self.password_label.setStyleSheet("color: rgb(234, 0, 3)")
        self.password_label.setObjectName("password_label")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 90, 67, 29))
        self.label.setStyleSheet("color: rgb(163, 163, 163);\n"
                                 "font-size: 18px;")
        self.label.setObjectName("label")
        self.create_account = QtWidgets.QPushButton(Form)
        self.create_account.setGeometry(QtCore.QRect(210, 490, 211, 41))
        self.create_account.setStyleSheet("font-size: 20px;\n"
                                          "color: rgb(163, 163, 163);\n"
                                          "border-radius: 10px;\n"
                                          "border: 1px solid rbg(0, 0, 0)")
        self.create_account.setObjectName("create_account")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(210, 260, 471, 61))
        self.password.setStyleSheet("color: rgb(163, 163, 163);\n"
                                    "font-size: 18px;\n"
                                    "border-radius: 10px;\n"
                                    "border: 2px solid rgb(100, 0, 0);\n"
                                    "background-color: rgb(79, 79, 79)")
        self.password.setText("")
        self.password.setObjectName("password")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(210, 360, 159, 29))
        self.label_5.setStyleSheet("color: rgb(163, 163, 163);\n"
                                   "font-size: 18px;")
        self.label_5.setObjectName("label_5")
        self.new_pass_label = QtWidgets.QLabel(Form)
        self.new_pass_label.setEnabled(True)
        self.new_pass_label.setGeometry(QtCore.QRect(400, 360, 208, 21))
        self.new_pass_label.setStyleSheet("color: rgb(234, 0, 3)")
        self.new_pass_label.setObjectName("new_pass_label")
        self.new_password = QtWidgets.QLineEdit(Form)
        self.new_password.setGeometry(QtCore.QRect(210, 400, 471, 61))
        self.new_password.setStyleSheet("color: rgb(163, 163, 163);\n"
                                        "font-size: 18px;\n"
                                        "border-radius: 10px;\n"
                                        "border: 2px solid rgb(100, 0, 0);\n"
                                        "background-color: rgb(79, 79, 79)")
        self.new_password.setText("")
        self.new_password.setObjectName("new_password")
        self.login_or_pass = QtWidgets.QLabel(Form)
        self.login_or_pass.setEnabled(True)
        self.login_or_pass.setGeometry(QtCore.QRect(260, 20, 328, 29))
        self.login_or_pass.setStyleSheet("color: rgb(234, 0, 3)")
        self.login_or_pass.setObjectName("login_or_pass")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Secret Storage"))
        self.back.setText(_translate("Form", "<- Назад"))
        self.pass_changed.setText(_translate("Form",
                                             "<html><head/><body><p><span style=\" font-size:20pt;\">Пароль изменен</span></p></body></html>"))
        self.label_2.setText(_translate("Form",
                                        "<html><head/><body><p><span style=\" font-size:18pt;\">Текущий пароль</span></p></body></html>"))
        self.login_label.setText(_translate("Form",
                                            "<html><head/><body><p><span style=\" font-size:16pt;\">Введите логин!</span></p></body></html>"))
        self.password_label.setText(_translate("Form",
                                               "<html><head/><body><p><span style=\" font-size:16pt;\">Введите пароль!</span></p></body></html>"))
        self.label.setText(_translate("Form",
                                      "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                      "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                      "p, li { white-space: pre-wrap; }\n"
                                      "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18px; font-weight:400; font-style:normal;\">\n"
                                      "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Логин</span></p></body></html>"))
        self.create_account.setText(_translate("Form", "Сменить пароль"))
        self.label_5.setText(_translate("Form",
                                        "<html><head/><body><p><span style=\" font-size:18pt;\">Новый пароль</span></p></body></html>"))
        self.new_pass_label.setText(_translate("Form",
                                               "<html><head/><body><p><span style=\" font-size:14pt;\">Введите новый пароль!</span></p></body></html>"))
        self.login_or_pass.setText(_translate("Form",
                                              "<html><head/><body><p><span style=\" font-size:18pt;\">Неверный логин или пароль!</span></p></body></html>"))
